//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notify
    {
        public int ID { get; set; }
        public string Notify1 { get; set; }
        public Nullable<int> Personal_Id { get; set; }
    
        public virtual Personal Personal { get; set; }
    }
}
