//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personal()
        {
            this.Notifies = new HashSet<Notify>();
        }
    
        public int ID { get; set; }
        public string Insider_Name { get; set; }
        public string Insider_Name_arabic { get; set; }
        public string Company_Name { get; set; }
        public string Company_Name_arabic { get; set; }
        public string Position { get; set; }
        public string Position_arabic { get; set; }
        public string UAE_Resident { get; set; }
        public string UAE_Resident_arabic { get; set; }
        public string Emirates_ID { get; set; }
        public string Passport_Number { get; set; }
        public string Mobile_Number { get; set; }
        public string Office_Number { get; set; }
        public string User_Id { get; set; }
        public string Email_Address_2 { get; set; }
        public string Trade_License { get; set; }
        public string Security_Code { get; set; }
        public string Other_information { get; set; }
        public Nullable<System.DateTime> ID_Expire_Date { get; set; }
        public string ID_Upload { get; set; }
        public Nullable<System.DateTime> Passport_Expire_Date { get; set; }
        public string Passport_Upload { get; set; }
        public Nullable<System.DateTime> Company_TL_Expire_Date { get; set; }
        public string Comany_TL_Upload { get; set; }
        public string status { get; set; }
        public string Comany_Image_Upload { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notify> Notifies { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
